---
title: "Vize_Rapor_200401081_Enes_Guler"
author: "Enes"
date: "2024-04-24"
output: html_document
---

## Q.1.1 İş tanımı

Şirketimiz "DataFinance Danışmanlık" olarak müşterilerimize veri odaklı çözümler sunarak operasyonel etkinliği artırmayı hedefliyoruz. Müşterilerimize veri analizi ve finans alanlarda danışmanlık hizmetleri sunar.

## Q.1.2 Problem ve ihtiyaç

Şirketimizin karşılaştığı temel problem, müşterilerin iş süreçlerini veriye dayalı olarak optimize etme ihtiyacıdır. Birçok işletme, sahip oldukları veriyi etkili bir şekilde analiz edip yorumlayacak kaynaklara ve uzmanlığa sahip değildir. Dolayısıyla, müşterilerimizin karşılaştığı temel ihtiyaç, iş süreçlerinde veri odaklı analitik hizmetlerin sağlanmasıdır.

## Q.1.3 Çözüm

Çözüm Önerisi - Veri Seti Tanımı:
Bu projede kullanılacak olan veri seti, müşterilerin iş süreçlerini optimize etmek için kritik bir rol oynayacaktır. Bitcoin fiyat verileri gibi finansal veriler, müşterilerin yatırım kararlarını etkileyen önemli faktörlerden biridir. Bu nedenle, bu analiz için kullanılacak veri seti, Bitcoin fiyat hareketlerini içermelidir.

Çözüm Önerisi - Planlanan Analiz:
Bu analizde, Bitcoin fiyat verileri üzerinde Fibonacci analizi yapılacaktır. Fibonacci analizi, Bitcoin fiyat hareketlerini anlamak ve gelecekteki fiyat hareketlerini tahmin etmek için kullanılacaktır.

Çözüm Önerisi - Planlanan Analiz Sonuçları:
Planlanan analiz sonuçları, müşterinin yatırım kararlarını desteklemek için önemli bilgiler sağlayacak. Fibonacci analizi sonuçları, müşterilere Bitcoin fiyatlarının olası destek ve direnç seviyelerini gösterecek ve bu da yatırım kararlarını etkileyecektir.
